#!/bin/bash
awk -F: '($3>=1000)&&($1!="nobody"){print$1}' /etc/passwd > users.txt

while read p; do
        k=1
        user=$(sed -n "$k,$k"'p' users.txt)
        echo "$user"':[ebZ<8[YsW9]MzG$'| chpasswd
        ((k=k+1))
done < users.txt


